version: '3.8'

services:
  app:
    container_name: whatsapp_web_api
    build: .
    # image: chrishubert/whatsapp-web-api:latest # Pull the image from Docker Hub
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      # Core WhatsApp API Configuration
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL:-http://localhost:3000/localCallbackExample}
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=${ENABLE_LOCAL_CALLBACK_EXAMPLE:-TRUE}
      - MAX_ATTACHMENT_SIZE=${MAX_ATTACHMENT_SIZE:-5000000}
      - SET_MESSAGES_AS_SEEN=${SET_MESSAGES_AS_SEEN:-TRUE}
      - DISABLED_CALLBACKS=${DISABLED_CALLBACKS:-message_ack|message_reaction}
      - ENABLE_SWAGGER_ENDPOINT=${ENABLE_SWAGGER_ENDPOINT:-TRUE}
      
      # Optional Security
      - API_KEY=${API_KEY}
      
      # Rate Limiting (Optional)
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-1000}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-1000}
      
      # WhatsApp Web Version (Optional)
      - WEB_VERSION=${WEB_VERSION}
      - WEB_VERSION_CACHE_TYPE=${WEB_VERSION_CACHE_TYPE:-none}
      
      # Session Management
      - RECOVER_SESSIONS=${RECOVER_SESSIONS:-FALSE}
      - SESSIONS_PATH=${SESSIONS_PATH:-./sessions}
      
      # Worker Registration (for distributed setup)
      - WORKER_ID=${WORKER_ID:-worker-1}
      - WORKER_URL=${WORKER_URL:-http://localhost:3000}
      - WHATSAPP_MANAGER_URL=${WHATSAPP_MANAGER_URL}
      - MAX_SESSIONS=${MAX_SESSIONS:-10}
      
      # Server Configuration
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ./sessions:/usr/src/app/sessions # Mount the local ./sessions/ folder to the container's /usr/src/app/sessions folder
